config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'

  devise_for :users
  resources :flowers do
    resources :comments
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :favorites, only: [:index]
    get :favorites, on: :collection
  end
  get 'flowers/index'
  resources :maps
  resources :tops, only: [:index]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :flower
  belongs_to :user

  validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_flower, only: [:create, :edit, :update]
  before_action :check_comment_owner, only: [:edit, :update, :destroy]

  def create
    @comment = @flower.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = 'コメントが投稿されました'
    else
      flash[:notice] = 'コメントを投稿できませんでした...'
    end
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to flower_path(@flower) }
      end
    end
  end

  def edit
    @comment = @flower.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @flower.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end
  
  private

  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def set_flower
    @flower = Flower.find(params[:flower_id])
  end

  def check_comment_owner
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      redirect_to flower_path(@flower), alert: 'アクセスが制限されています。'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [flower, comment], local: false, html: { class: "comment-form" }) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t("errors.template.header", model: t("activerecord.models.flower"), count: flower.errors.count) %>
      </h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{flower.id}", data: { test_id: "test_comment_content" } %>
  </div>
  <%= form.submit class: "submit-button" %>
<% end %>

app/views/comments/_form.html.erb
<!-- この記述がflowerのshow画面に表示されるコメント入力欄になる -->
<%= form_with(model: [flower, comment], local: false, html: { class: "comment-form" }) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2>
      <%= t("errors.template.header", model: t("activerecord.models.flower"), count: flower.errors.count) %>
      </h2>
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <%= form.submit class: "submit-button" %>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <div class="comment-content" id="this_comment_<%= comment.id %>">
        <div class="user-profile">
          <%= link_to user_path(comment.user.id) do %>
            <% if comment.user.profile_image.attached? %>
              <%= image_tag comment.user.profile_image.variant(resize: "40x40", auto_orient: true, quality: 100), class: "rounded-small-profile-image" %>
            <% else %>
              <%= image_tag "default_profile_image.png", class: "rounded-small-profile-image", width: 40, height: 40 %>
            <% end %>
            <p class="user-name"><%= comment.user.name %></p>
          <% end %>
        </div>
        <div class="comment-text">
          <p><%= comment.content %></p>
        </div>
        <div class="comment-actions">
          <% if current_user == comment.user %>
            <%= link_to 'コメントを編集', edit_flower_comment_path(flower, comment), remote: true, class: 'custom-link' %>
            <%= link_to 'コメントを削除', flower_comment_path(comment.flower_id, comment.id), method: :delete, remote: true, 
                                        data: { confirm: "本当に削除しますか?"}, class: 'custom-link' %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
<% if flash[:notice] %>
  $('#flash-message').html('<%= j render partial: "shared/flash", locals: { flash: flash } %>');
<% else %>
  $('#flash-message').empty();
<% end %>

// コメントが正常に保存された場合、フラッシュメッセージを消す
<% if @comment.errors.blank? %>
  $('#flash-message').empty();
<% end %>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', flower: @flower, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.flower.comments, flower: @comment.flower }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");
$("#success").html("<%= j flash[:success] %>");