config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'

  devise_for :users
  resources :flowers do
    resources :comments
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :favorites, only: [:index]
    get :favorites, on: :collection
  end
  get 'flowers/index'
  resources :maps
  resources :tops, only: [:index]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  def index
  end
end

app/views/tops/index.html.erb
<div class="feature-wrapper">
  <h1>PetalPushは花の共有アプリです</h1>

  <div class="feature-container">
    <p>PetalPushとは、街や公園で咲く花を共有するためのアプリケーションです。</p>
    <p>桜や紅葉、ひまわりやコスモスなど、さまざまな花の開花状況や花の名前を知ることができます。</p>
    <p>地図情報を元に、現在地周辺で咲いている花を検索することも可能です。</p>
    <p><%= link_to '今すぐPetalPushを使ってみる!', flowers_path, class: 'submit-button' %></p>
  </div>

  <h2>機能について</h2>
  <div class="features-grid">
    <div class="feature-container">
      <div class="feature-title">花の投稿機能</div>
      <ul class="feature-list">
        <li>好きな花の写真を撮影し、アプリに簡単にアップロード！</li>
        <li>投稿された花の情報はGoogleマップ上で見ることができ、花を探すのが楽しくなります。</li>
        <li>投稿した花の情報は、他のユーザーにも共有されます。</li>
      </ul>
    </div>
    <div class="feature-container">
      <div class="feature-title">花の詳細機能</div>
      <ul class="feature-list">
        <li>他のユーザーが投稿した花の情報を、一覧画面で閲覧できます。</li>
        <li>好みの花や特定の条件で、投稿された花の情報を検索できます。</li>
      </ul>
    </div>
    <div class="feature-container">
      <div class="feature-title">コメント機能</div>
      <ul class="feature-list">
        <li>投稿された花の情報に対して、感想や質問などのコメントを気軽に投稿できます。</li>
        <li>コメントを通じて、他のユーザーとの交流が楽しめます。</li>
      </ul>
    </div>
    <div class="feature-container">
      <div class="feature-title">いいね機能</div>
      <ul class="feature-list">
        <li>心に響いた投稿を「お気に入り」をすることで、気に入った花を簡単に記録できます。</li>
        <li>いいねした投稿はマイページでいつでも確認でき、花の思い出が蘇ります。</li>
      </ul>
    </div>
  </div>
    <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'custom-link' %>
    <%= link_to 'ゲストログイン（管理者用）', users_guest_admin_sign_in_path, method: :post, class: 'custom-link' %>
</div>