config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'

  devise_for :users
  resources :flowers do
    resources :comments
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :favorites, only: [:index]
    get :favorites, on: :collection
  end
  get 'flowers/index'
  resources :maps
  resources :tops, only: [:index]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/flower.rb
class Flower < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  #flowerをお気に入りした人の情報を取得する
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 300 }
  validate :address_or_coordinates_present

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.ransackable_attributes(auth_object = nil)
    %w[name description address]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[flower]
  end
  private

  def address_or_coordinates_present
    if address.blank? && (latitude.blank? || longitude.blank?)
      errors.add(:base, "住所または位置情報を入力してください。")
    end
  end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :ensure_correct_user, only: %i[ edit update destroy ]

  def index
    @flowers = Flower.all
    @q = Flower.ransack(params[:q])
    @flowers = @q.result(distinct: true).order("created_at desc")
    gon.flowers = @flowers.map do |flower|
      {
      id: flower.id,
      name: flower.name,
      latitude: flower.latitude,
      longitude: flower.longitude,
      image_url: rails_blob_url(flower.image)
    }
    end
  end

  def show
    @comments = @flower.comments
    @comment = @flower.comments.build
    if user_signed_in?
      @favorite = current_user.favorites.find_by(flower_id: @flower.id)
    else
      @favorite = nil
    end
  end

  def new
    @flower = Flower.new
  end

  def edit
  end

  def create
    @flower = current_user.flowers.build(flower_params)
    return render :new if params[:back]
    if @flower.save
      redirect_to flowers_path, notice: '画像を投稿しました'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @flower.update(flower_params)
        format.html { redirect_to flower_url(@flower), notice: "投稿を編集しました" }
        format.json { render :show, status: :ok, location: @flower }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flower.destroy

    respond_to do |format|
      format.html { redirect_to flowers_url, notice: "投稿を削除しました" }
      format.json { head :no_content }
    end
  end

  private
  
  def set_flower
    @flower = Flower.find(params[:id])
  end

  def flower_params
    params.require(:flower).permit(:name, :description, :image, :address, :latitude, :longitude)
  end

  def ensure_correct_user
    @user = @flower.user
    unless @user == current_user
      redirect_to flowers_path, alert: "アクセス権限がありません。"
    end
  end
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/views/flowers/_form.html.erb
<%= form_with(model: flower) do |form| %>
  <% if flower.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t("errors.template.header", model: t("activerecord.models.flower"), count: flower.errors.count) %>
      </h2>
      <ul>
        <% flower.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-container">
    <div class="field">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, placeholder: '花の名前を入力してください', class: "form-input" %>
    </div>

    <div class="field">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, placeholder: '花の詳細を入力してください', class: "form-input" %>
    </div>

    <div class="field">
      <%= form.label :image, t('labels.image'), class: "form-label" %>
      <%= form.file_field :image, class: "form-input" %><br>
    </div>

    <div class="field">
      <%= form.label :address, class: "form-label" %>
      <%= form.text_field :address, placeholder: '住所や建物の名前を入力してください', class: "form-input" %>
    </div>

    <div class="field" hidden>
      <%= form.label :latitude %>
      <%= form.number_field :latitude, step: 'any', id: 'lat' %>
    </div>

    <div class="field" hidden>
      <%= form.label :longitude %>
      <%= form.number_field :longitude, step: 'any', id: 'lng' %>
    </div>

  <div class="content">
    <div id="map"></div>
    <style>
      #map {
        height: 300px;
        width: 300px;
      }
    </style>
    <script>
      var map;
      var marker;

      function initMap() {
        const defaultCenter = { lat: 35.4550426, lng: 139.6312741 };
        const mapOptions = {
          zoom: 6,
          center: defaultCenter,
        };

        map = new google.maps.Map(document.getElementById("map"), mapOptions);

        map.addListener("click", function (e) {
          getClickLatLng(e.latLng, map);
        });

        const addressField = document.getElementById("address");
        const latHiddenField = document.getElementById("lat");
        const lngHiddenField = document.getElementById("lng");
        const service = new google.maps.places.PlacesService(map);

        addressField.addEventListener("change", (e) => {
          const address = e.target.value;
          const request = {
            query: address,
            fields: ["name", "geometry"],
          };
          service.findPlaceFromQuery(request, function (results, status) {
            if (status === google.maps.places.PlacesServiceStatus.OK) {
              for (let i = 0; i < results.length; i++) {
                const place = results[i];
                const lat = place.geometry.location.lat();
                const lng = place.geometry.location.lng();
                const latLng = { lat: lat, lng: lng };
                getClickLatLng(latLng, map);
                latHiddenField.value = lat;
                lngHiddenField.value = lng;
              }
            }
          });
        });
      }

      window.addEventListener("DOMContentLoaded", initMap);

      function getClickLatLng(latLng, map) {
        if (marker) {
          marker.setMap(null);
        }

      });
    });
  }

  function getClickLatLng(latLng, map) {
    if (marker) {
      marker.setMap(null);
    }

    marker = new google.maps.Marker({
      position: latLng,
      map: map,
    });

    map.panTo(latLng);

    document.getElementById("lat").value = latLng.lat();
    document.getElementById("lng").value = latLng.lng();

    const geocoder = new google.maps.Geocoder();
    geocoder.geocode({ location: latLng, region: 'JP' }, function (results, status) {
      if (status === "OK") {
        if (results[0]) {
          const address_components = results[0].address_components;
          const long_name = address_components.map(component => component.long_name);
          document.getElementById("address").value = long_name.join(' ');
        } else {
          console.log("No results found");
        }
      } else {
        console.log("Geocoder failed due to: " + status);
      }
    });
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
    
  <div class="actions">
    <%= form.submit "登録", class: "submit-button" %>

        marker = new google.maps.Marker({
          position: latLng,
          map: map,
        });

        console.log(marker);

        map.panTo(latLng);

        document.getElementById("lat").value = latLng.lat();
        document.getElementById("lng").value = latLng.lng();
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=places&callback=initMap" async defer></script>
      
    <div class="actions">
      <%= form.submit "登録", class: "submit-button" %>
    </div>

  </div>
<% end %>

app/views/flowers/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class ="search-form">
    <%= f.search_field :name_or_description_or_address_cont, class: 'form-control', placeholder: '検索ワードを入力してください' %>
    <%= f.submit '検索', class: 'search-button' %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h1>投稿の編集</h1>

<%= render 'form', flower: @flower %>

<%= link_to '詳細', @flower, class: 'back-link' %>
<%= link_to '戻る', flowers_path, class: 'back-link' %>

app/views/flowers/index.html.erb
<% if current_user.try(:admin?) %>
  <h1>管理者ページ</h1>
<% else %>
  <h1>花一覧</h1>
<% end %>

<%= link_to '花を投稿する', new_flower_path, class: "submit-button" %>
<%= render 'search', q: @q, url: flowers_path %>

<div id='map'></div>
  <style>
    #map {
      height: 500px;
      width: 100%;
    }
  </style>
  <script>
    var map;
    var bounds;
    var marker = [];
    var infoWindow = [];
    // コントローラーで定義したインスタンス変数(@flowers)を代入
    var markerData = gon.flowers;
        
    function initMapindex() {
      // マップの初期化
      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 9,
        center: {lat: 35.4550426, lng: 139.6312741}
      });

      // @flowersの数だけ繰り返し処理を行い、マーカーと吹き出しを複数表示させる
      for (var i = 0; i < markerData.length; i++) {
        let id = markerData[i]['id']

        // 各スポットの緯度経度を算出
        markerLatLng = new google.maps.LatLng({
          lat:  Number(markerData[i]['latitude']),
          lng:  Number(markerData[i]['longitude'])
        });

        // 各スポットのマーカーを作成
        marker[i] = new google.maps.Marker({
          position: markerLatLng,
          map: map
        });

        // 各スポットの吹き出しを作成
        infoWindow[i] = new google.maps.InfoWindow({
          // 吹き出しの内容
          content: `<a href='/flowers/${ id }' class='custom-link'>${ markerData[i]['name'] }<br><img src="${ markerData[i]['image_url'] }" width="100" /></a>`
        });

        // マーカーにクリックイベント追加
        markerEvent(i);
      }
      map_adjust();
    }

    // マーカーをクリックしたら吹き出しを表示
    function markerEvent(i) {
      marker[i].addListener('click', function () {
        infoWindow[i].open(map, marker[i]);
      });

    }

    function map_adjust(){
      var latMin = 90;  //緯度は-90～90の値
      var latMax = -90;
      var lngMin = 180;  //経度は-180～180の値
      var lngMax = -180;

      if (markerData.length == 1){
        map = new google.maps.Map(document.getElementById('map'), {
          center: {
            lat: gon.flower.latitude,
            lng: gon.flower.longitude
          },
        });

      }else{
        for (var i = 0; i < markerData.length; i++) {
          var thisLat = markerData[i]['latitude'];
          var thisLng = markerData[i]['longitude'];
          latMin = Math.min(latMin, thisLat);  //最小経度
          latMax = Math.max(latMax, thisLat);  //最大経度
          lngMin = Math.min(lngMin, thisLng);  //最小緯度
          lngMax = Math.max(lngMax, thisLng);  //最大緯度

          var min = new google.maps.LatLng(latMin, lngMin);  //最小緯度経度（南西）
          var max = new google.maps.LatLng(latMax, lngMax);  //最大緯度経度（北東）
          var latLngBounds = new google.maps.LatLngBounds(min, max);
          //マーカーが全て地図に収まるように調整
          map.fitBounds(latLngBounds);  
        }
      }
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMapindex" async defer></script>

<div class="grid-container">
  <% @flowers.each do |flower| %>
    <div class="grid-item">
      <div class="user-info">
        <div>
          <%= link_to user_path(flower.user.id) do %>
            <% if flower.user.profile_image.attached? %>
              <%= image_tag flower.user.profile_image.variant(resize: "40x40", auto_orient: true, quality: 100), class: "rounded-small-profile-image" %>
            <% else %>
              <%= image_tag "default_profile_image.png", alt: "デフォルトプロフィール画像", class: "rounded-small-profile-image", size: "40x40" %>
            <% end %>
        </div>
        <div class="user-name"><%= flower.user.name %></div>
        <% end %>
      </div>
      <% if flower.image.attached? %>
        <%= image_tag flower.image.variant(resize_and_pad: [200, 200]) %>
      <% end %>
      <div class="image-info">
        <div class="flower-name"><%= flower.name %></div>
        <div class="flower-description"><%= flower.description %></div>
        <div class="flower-address"><%= flower.address %></div>
        <div class="created-at"><%= time_ago_in_words(flower.created_at) %>前</div>
      </div>
      <div class="actions">
        <%= link_to '詳細', flower %>
        <% if user_signed_in? && current_user == flower.user %>
          <%= link_to '編集', edit_flower_path(flower) %>
          <%= link_to '削除', flower, method: :delete, data: { confirm: '本当に削除しても良いですか?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/flowers/new.html.erb
<h1>花の新規投稿</h1>

<%= render 'form', flower: @flower %>

<%= link_to '戻る', flowers_path, class: 'back-link' %>

app/views/flowers/show.html.erb
<h1>花の詳細情報</h1>

<div class="detail-container">
  <div class="detail-item">
    <div class="image-info">
      <div class="user-name">
        <%= @flower.user.name %>
      </div>

      <div class="created-at">
        <%= time_ago_in_words(@flower.created_at) %>前</div>

      <div class="flower-name">
        <%= @flower.name %>
      </div>

      <div class="flower-name">
        <%= @flower.description %>
      </div>

      <div class="flower-name">
        <% if @flower.image.attached? %>
          <%= image_tag @flower.image.variant(resize_to_limit: [200, 200]) %>
        <% end %>
      </div>

      <div class="flower-name">
        <%= @flower.address %>
      </div>

      <div class="flower-name">
        <script type="text/javascript">
          function initMapshow() {
            var test = {lat: <%= @flower.latitude %>, lng: <%= @flower.longitude %>};
            var map = new google.maps.Map(document.getElementById('map'), {
                      zoom: 10, 
                      center: test
                      });
            var transitLayer = new google.maps.TransitLayer();
            transitLayer.setMap(map);
            var contentString = '住所：<%= @flower.address %>';
            var infowindow = new google.maps.InfoWindow({
              content: contentString
            });
            var marker = new google.maps.Marker({
                          position:test,
                          map: map,
                          title: contentString
                        });
            marker.addListener('click', function() {
              infowindow.open(map, marker);
            });
          }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMapshow" async defer></script>
        <style type="text/css">
          #map {
            height: 200px;
            width: 200px;
          }
        </style>
        <div id="map"></div>
      </div>

      <div class="flower-name" id: "favorite-button" >
        <% if user_signed_in? %>
          <% unless @flower.favorite_users == current_user %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id), method: :delete, class: "custom-link" %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(flower_id: @flower.id), method: :post, class: "custom-link" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="action">
      <p>コメント一覧</p>
    </div>

    <!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
    <div id="comments_area">
      <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
      <%= render partial: 'comments/index', locals: { comments: @comments, flower: @flower } %>
    </div>

    <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/form', locals: { comment: @comment, flower: @flower } %>
  </div>
</div>

<%= link_to '戻る', flowers_path, class: 'back-link' %>