config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tops#index'

  devise_for :users
  resources :flowers do
    resources :comments
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    resources :favorites, only: [:index]
    get :favorites, on: :collection
  end
  get 'flowers/index'
  resources :maps
  resources :tops, only: [:index]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <title>PetalPush</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= stylesheet_link_tag 'flowers' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <header class ="header">
      <div class ="header-icon">
        <% if user_signed_in? %>
          <%= link_to 'プロフィール', user_path(current_user.id) %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% if current_user.admin? %>
              <%= link_to '管理者ページ', rails_admin_path %>
            <% end %>
          <% else %>
          <%= link_to 'ログイン', new_user_session_path %>
          <%= link_to 'サインアップ', new_user_registration_path %>
        <% end %>
      </div>
      <div class="header-center-link">
        <%= link_to 'PetalPush', flowers_path, class: 'custom-link' %>
      </div>
    </header>

  <div class="content">
    <div id="success"><%= flash[:success] %>
      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>
    </div>
    <%= yield %>
  </div>

    <footer class ="footer">
      <%= link_to "トップページへ", tops_path, class: 'footer-link' %>
    </footer>
  </body>
</html>